/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Blog: typeof import('./src/components/blog.vue')['default']
    'Blog.new': typeof import('./src/components/blog.new.vue')['default']
    Icon: typeof import('./src/components/icon.vue')['default']
    'Index.old': typeof import('./src/components/index.old.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
